name: polyp-tf-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py
  - asn1crypto
  - astor
  - blas
  - blinker
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - cryptography
  - cycler
  - cytoolz
  - dask-core
  - decorator
  - freetype
  - gast
  - geos
  - h5py
  - hdf5
  - icu
  - idna
  - imagecodecs-lite
  - imageio
  - imgaug
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libopencv=3.4.2
  - libpng=1.6.37
  - markdown=3.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mkl
  - mkl-service
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - networkx=2.4
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - pillow=7.1.2
  - pip=20.0.2
  - protobuf=3.11.4
  - py-opencv=3.4.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil
  - python_abi=3.7
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - rsa=4.0
  - scikit-image=0.17.2
  - scipy=1.4.1
  - setuptools=46.1.3
  - shapely=1.7.0
  - sip=4.19.8
  - six=1.14.0
  - sqlite=3.31.1
  - tensorboard=2.1.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - tifffile=2020.6.3
  - tk=8.6.10
  - toolz=0.10.0
  - werkzeug=0.14.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.4
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - lxml==4.5.0
    - tqdm==4.44.1
